import Head from 'next/head'
import styles from '../styles/Home.module.css'

import dynamic from 'next/dynamic'

const HomePage = dynamic(() => import('../components/homepage/HomePage'), {
  ssr: false
})

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shakti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomePage />
      </main>
    </div>
  )
}
